AllCops:
  Include:
    - 'lib/**/*'
  Exclude:
    - 'daru-io.gemspec'
    - 'Rakefile'
    - 'Gemfile'
    - 'Guardfile'
    - '**/*.erb'
    - 'spec/*'
    - 'spec/**/*'
    - 'vendor/**/*'
    - 'benchmarks/*'
    - 'profile/*'
  DisplayCopNames: true
  TargetRubyVersion: 2.0

# Preferred codebase style ---------------------------------------------
Style/ExtraSpacing:
  AllowForAlignment: true

Style/FormatString:
  EnforcedStyle: percent

Style/AndOr:
  EnforcedStyle: conditionals

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/SpaceInsideBlockBraces:
  EnforcedStyle: space

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/EmptyElse:
  EnforcedStyle: empty

Metrics/LineLength:
  Max: 120

Metrics/ModuleLength:
  Max: 200

Metrics/ClassLength:
  Max: 200

Style/ParallelAssignment:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/SpaceAfterComma:
  Enabled: false

Style/SpaceAroundOperators:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

# Neither of prefered styles are good enough :(
Style/BlockDelimiters:
  Enabled: false

# Current preferred metrics --------------------------------------------
# Better values are encouraged, but not required.
Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 15

Metrics/CyclomaticComplexity:
  Max: 7

# TODO -----------------------------------------------------------------

Style/Documentation:
  Enabled: false