language:
  ruby

rvm:
  - '2.1'
  - '2.2'
  - '2.3.0'
  - '2.4.0'

script:
  - bundle exec rspec
  - bundle exec rubocop

services:
  - mongodb

before_install:
  - sleep 15
  - mongo test --eval 'db.addUser("travis", "test");'

install:
  - gem install bundler
  - gem install rainbow -v '2.2.1'
  - bundle install